version: "3"

services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: hohoprince/nginx
    ports:
    - "80:80"
    depends_on:
    - carrot-market
    - carrot-chat

  carrot-market:
    container_name: carrot-market
    build:
      dockerfile: Dockerfile
      context: ./carrot-market
    image: hohoprince/carrot-market
    ports:
    - "8080:8080"
  
  carrot-chat:
    container_name: carrot-chat
    build:
      dockerfile: Dockerfile
      context: ./carrot-chat
    image: hohoprince/carrot-chat
    ports:
    - "8888:8888"
    

  
